theme:
  name: material
  font:
    text: Hind
    code: Overpass Mono
  icon:
    logo: material/account-group
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vsrikrish

site_name: Srikrishnan Group Lab Manual
repo_name: srikrishnan-lab/lab-manual
repo_url: https://github.com/srikrishnan-lab/lab-manual

markdown_extensions:
  - admonition
  - pymdownx.details
  - smarty
  - footnotes
  - attr_list
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - pdf-export:
      combined: false
